markdown_extensions:
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 3
      title: On this page
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
    # auto_append:
    # - docs/assets/glossary/snippets.md  # Causes massive slowdown. Also, bad.
  - attr_list
  - abbr
  - neoteroi.cards
  - neoteroi.timeline
  - footnotes
# extra:
#   analytics:
#     provider: google
#     property: 
plugins:
  - search
  - awesome-pages:
      filename: .pages.yml
 # - git-authors
  - tags:
      tags: false  # This will keep tags for the purpose of indexing, but not display on page.
  - git-revision-date-localized:
      enable_creation_date: false
  - macros:
      on_error_fail: !ENV [TEST_ENV, false]
      verbose: !ENV [TEST_ENV, false]
      include_dir: overrides
repo_name: GitHub
repo_url: https://github.com/nesi/agdr-docs-concept
edit_uri: edit/main/docs/
site_description: AGDR
site_dir: public
site_name: AGDR
site_url: https://github.com/nesi/agdr-docs-concept
extra_css:
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/footer.css
  - assets/stylesheets/my.css
  - assets/stylesheets/theme.css
theme:
  custom_dir: overrides
  favicon: assets/icons/favicon.ico
  features:
    - navigation.indexes
    - navigation.instant          # Single Page Application
    - navigation.instant.prefetch # Start loading page on link hover. Insiders only
    - navigation.top              # 'Return to top' button
    - navigation.tracking         # Put anchor in URL
    - navigation.path             # Breadcrumbs. Insiders only
    - content.code.copy
    - content.action.edit
    - header.site_name_homepage
  language: en
  logo: assets/icons/logo.svg
  name: material
  palette:
    - primary: custom
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - primary: custom
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
# Page tree
nav:
  - Home: index.md
  - User Guides:
    - user-guides/index.md
    - Navigating the data repository: user-guides/navigating.md
    - Requesting access to data: user-guides/requesting.md
    - Accessing data hosted on NeSI Globus endpoint: user-guides/globus.md
    - Submission Process: user-guides/submission.md
  - Releases:
    - releases/index.md
    - Known Deficiencies: releases/deficiencies.md
    - data.agdr.org.nz 16 January 2024: releases/16Jan2024.md
    - data.agdr.org.nz 16 October 2023: releases/16Oct2023.md
    - data.agdr.org.nz 22 June 2023: releases/22June2023.md
