site_name: AGDR
repo_name: GitHub
repo_url: https://github.com/nesi/agdr-docs
edit_uri: edit/main/docs/
site_description: AGDR
site_dir: public
site_url: https://docs.agdr.org.nz/
theme:
  custom_dir: overrides
  favicon: assets/icons/favicon.ico
  language: en
  logo: assets/icons/ga_logo_alpha.svg
  name: material
  palette:
    - primary: custom
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - primary: custom
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.path
    - content.code.copy
    - content.action.edit
    - header.site_name_homepage
hooks:
  - mkdocs_hooks.py
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 3
      title: On this page
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets: null
extra:
  analytics:
    provider: google
    property: G-XJVS54JJBF
plugins:
  - search
  - open-in-new-tab
  - redirects:
      map_file: redirect_map.yml
  - awesome-pages:
      filename: .pages.yml
  - tags:
      tags: false
  - git-revision-date-localized:
      enable_creation_date: false
  - macros:
      include_dir: overrides
      module_name: macro_hooks
      on_error_fail: true
      verbose: false
extra_css:
  - assets/stylesheets/footer.css
  - assets/stylesheets/my.css
  - assets/stylesheets/theme.css
extra_javascript:
  - assets/javascripts/general.js
