# Page tree
nav:
  - Home: index.md
  - User Guides:
    - user-guides/index.md
    - Navigating the data repository: user-guides/navigating.md
    - Requesting access to data: user-guides/requesting.md
    - Accessing data hosted on NeSI Globus endpoint: user-guides/globus.md
    - Submission Process: user-guides/submission.md
  - Releases:
    - releases/index.md
    - Known Deficiencies: releases/deficiencies.md
    - data.agdr.org.nz 16 January 2024: releases/16Jan2024.md
    - data.agdr.org.nz 16 October 2023: releases/16Oct2023.md
    - data.agdr.org.nz 22 June 2023: releases/22June2023.md

